### ISSUE TITLE
Light Gray dye items do not dye livery stickers

### ISSUE THREAD

**Issue by cogthecat** [kuenzign/CartLivery#4]
For some reason, light gray dye just doesn't do anything when combined with livery stickers. I've tested all of the vanilla dye items and all of the dyes from Biomes O' Plenty, and all but vanilla light gray work as expected. I've also tested this with several different sticker patterns, both dyed white/white and other colors, and it simply doesn't appear to have any crafting recipes at all for light gray.

Any insight?

**Comment by kuenzign** [comment]
I'll look into it, but I've been a bit busy with work.

**Comment by kuenzign** [comment]
Alright, I have a fix. For some reason Light Gray Dye is referred to as 'silver' and 'lightgray' in separate parts of Minecraft's/Forge's code.  I'm not sure why this is because that is the only color like that.  I've thrown in a small hack to fix it.  This issue has also alerted me to some errors as well as better design options.  I have fixed this issue and have also made the mod slighly more friendly for those who don't speak English. I thank you very much cogthecat, but I am honestly surprised a problem like this is just now being brought to my attention.  Anyways, the changes I have made will be released in the next version.  I was working on a nice feature in my spare time, but I'm not at all finished with it.  This means that I'm not sure when the next version will be released with the changes.
